language: node_js
node_js: v12.11.0
cache: 
  directories: node_modules
  npm: false
install: npm install
before_install: npm i -g npm@6.11.3
services: postgresql
before_script:
- psql -c 'create database EmployeeDB;' -U postgres
script: npm test
after_success: npm run coverage