language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - "node_modules"
install: 
    - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c "CREATE USER okpo WITH PASSWORD null;" -U postgres
script: npm test
after_success: npm run coverage
